rm -rf AndroidDynamicLoader/bin/* 
rm -rf AndroidDynamicLoader/.git 
rm -rf AndroidFlipViewDemo/bin/* 
rm -rf AndroidFlipViewDemo/.git 
rm -rf AndroidFlipViewLib/bin/* 
rm -rf AndroidFlipViewLib/.git 
rm -rf AndroidPanelDemo/bin/* 
rm -rf AndroidPanelDemo/.git 
rm -rf AndroidPanesLib/bin/* 
rm -rf AndroidPanesLib/.git 
rm -rf AndroidResideMenuDemo/bin/* 
rm -rf AndroidResideMenuDemo/.git 
rm -rf AndroidSlidingUpPanelLib/bin/* 
rm -rf AndroidSlidingUpPanelLib/.git 
rm -rf AndroidSwipeListViewLib/bin/* 
rm -rf AndroidSwipeListViewLib/.git 
rm -rf AndroidTouchGalleryDemo/bin/* 
rm -rf AndroidTouchGalleryDemo/.git 
rm -rf AndroidTouchGalleryLib/bin/* 
rm -rf AndroidTouchGalleryLib/.git 
rm -rf AntennaPod/bin/* 
rm -rf AntennaPod/.git 
rm -rf AntennaPodLib/bin/* 
rm -rf AntennaPodLib/.git 
rm -rf ApolloAudioPlayer/bin/* 
rm -rf ApolloAudioPlayer/.git 
rm -rf BlurEffectActivity/bin/* 
rm -rf BlurEffectActivity/.git 
rm -rf CameraActivity/bin/* 
rm -rf CameraActivity/.git 
rm -rf CardsExample/bin/* 
rm -rf CardsExample/.git 
rm -rf CardsUILib/bin/* 
rm -rf CardsUILib/.git 
rm -rf CircularProgressBarSample/bin/* 
rm -rf CircularProgressBarSample/.git 
rm -rf DownloadManager/bin/* 
rm -rf DownloadManager/.git 
rm -rf EmptyLayoutDemo/bin/* 
rm -rf EmptyLayoutDemo/.git 
rm -rf EmptyLayoutLib/bin/* 
rm -rf EmptyLayoutLib/.git 
rm -rf HoloCircularPrograssLib/bin/* 
rm -rf HoloCircularPrograssLib/.git 
rm -rf InfiniteViewPagerActivity/bin/* 
rm -rf InfiniteViewPagerActivity/.git 
rm -rf LightBoxPhotoProcessing/bin/* 
rm -rf LightBoxPhotoProcessing/.git 
rm -rf NineOldAndoridLib/bin/* 
rm -rf NineOldAndoridLib/.git 
rm -rf PhotUp/bin/* 
rm -rf PhotUp/.git 
rm -rf PhotoViewDemo/bin/* 
rm -rf PhotoViewDemo/.git 
rm -rf PhotoViewLib/bin/* 
rm -rf PhotoViewLib/.git 
rm -rf ProgrammingAdnroid2TouchMe/bin/* 
rm -rf ProgrammingAdnroid2TouchMe/.git 
rm -rf QuiltViewLib/bin/* 
rm -rf QuiltViewLib/.git 
rm -rf QuiltViewSample/bin/* 
rm -rf QuiltViewSample/.git 
rm -rf ReadAloudDemo/bin/* 
rm -rf ReadAloudDemo/.git 
rm -rf ResideMenuLib/bin/* 
rm -rf ResideMenuLib/.git 
rm -rf SwipeListViewExampleActivity/bin/* 
rm -rf SwipeListViewExampleActivity/.git 
rm -rf TweetLanes/bin/* 
rm -rf TweetLanes/.git 
rm -rf TweetLanesBeta/bin/* 
rm -rf TweetLanesBeta/.git 
rm -rf TweetLanesCoreLib/bin/* 
rm -rf TweetLanesCoreLib/.git 
rm -rf TweetLeans-TL-SocialNetLib/bin/* 
rm -rf TweetLeans-TL-SocialNetLib/.git 
rm -rf aarddict-android/bin/* 
rm -rf aarddict-android/.git 
rm -rf actionbarsherlock/bin/* 
rm -rf actionbarsherlock/.git 
rm -rf android-gif-drawableLib/bin/* 
rm -rf android-gif-drawableLib/.git 
rm -rf android-support-v7-appcompat/bin/* 
rm -rf android-support-v7-appcompat/.git 
rm -rf drag-sort-listview-lib/bin/* 
rm -rf drag-sort-listview-lib/.git 
rm -rf progressfragment/bin/* 
rm -rf progressfragment/.git 
rm -rf progressfragmentDemo/bin/* 
rm -rf progressfragmentDemo/.git 
rm -rf sherlockprogressfragment/bin/* 
rm -rf sherlockprogressfragment/.git 
rm -rf sherlockprogressframgmentdemo/bin/* 
rm -rf sherlockprogressframgmentdemo/.git 
rm -rf two-way-gridview-demo/bin/* 
rm -rf two-way-gridview-demo/.git 
rm -rf two-way-gridview-lib/bin/* 
rm -rf two-way-gridview-lib/.git 
rm -rf two-way-gridview-support-lib/bin/* 
rm -rf two-way-gridview-support-lib/.git 
